bill/urls.py
from django.conf.urls import url, include
# from expense.bill.urls import urlpatterns as bill_patterns
from . import views

app_name = 'bill'

urlpatterns = [
    # url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^list/$', views.list, name='list'),
    url(r'^add/$', views.add_bill, name='add_bill'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit_bill, name='edit_bill'),
    url(r'^(?P<pk>[^/]+)/details/$', views.detail, name='detail'),

]

employee/urls.py
from django.conf.urls import include, url
from employee import views

app_name = "employee"



urlpatterns = [
    url(r'^employee/', include([
        url(r'^$', views.index, name="list"),
        url(r'^select_list/$', views.select2_list, name="select_list"),
        url(r'^select_employee/$', views.select_employee, name="select_employee"),
        url(r'^select_designation/$', views.select_designation, name="select_designation"),
        url(r'^create/$', views.create, name='create'),
        url(r'^(?P<pk>[^/]+)/edit/', views.edit, name='edit'),
        url(r'^(?P<pk>[^/]+)/delete/', views.delete, name='delete'),
        url(r'^(?P<pk>[^/]+)/profile/', views.profile, name='profile'),
        url(r'^findoffice/', views.select_office, name="select_office"),
        url(r'^permissions/(?P<pk>[^/]+)/$', views.employee_permission, name='employee_permission'),
        url(r'^reports/salesbyemployee/$', views.sales_by_employee, name='sales_by_employee'),
        url(r'^reports/salesbyemployee/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.sales_by_employee, name="sales_by_employee"),
    ])),

]

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews
from rest_framework.authtoken import views

# from employee import views as employeeViews
from papercraneerp import allauth

urlpatterns = [
                  url(r'^$', erpAdminViews.dashboard),
                  url(r'^api-token-auth/', views.obtain_auth_token),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^accounts/password/change/$', allauth.login_after_password_change,
                      name='account_change_password'),  # Place before allauth urls to override
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^', include('employee.urls', namespace="employee")),
                  url(r'^', include('customer.urls', namespace="customer")),
                  url(r'^', include('product.urls', namespace="product")),
                  url(r'^chaining/', include('smart_selects.urls')),
                  url(r'^', include('service.urls', namespace="service")),
                  url(r'^', include('location.urls', namespace="location")),
                  url(r'^', include('invoice.urls', namespace="invoice")),
                  url(r'^', include('supplier.urls', namespace="supplier")),
                  url(r'^expense/', include('expense.urls', namespace="expense")),
                  url(r'^company/', include('company.urls', namespace="company")),
                  url(r'^vendor/', include('vendor.urls', namespace="vendor")),
                  url(r'^bill/', include('bill.urls', namespace="bill")),
                  url(r'^calendar/', include('calendarApp.urls', namespace="calendarApp")),
                  url(r'^discount/', include('discount.urls', namespace="discount")),
                  url(r'^package/', include('package.urls', namespace="package")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Saloon Administration'

register_dynamic_trees(
    compose_dynamic_tree('erp_admin'),
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('service'),
    compose_dynamic_tree('product'),
    compose_dynamic_tree('package'),
    compose_dynamic_tree('discount'),
    compose_dynamic_tree('supplier'),
    compose_dynamic_tree('vendor'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('calendarApp'),
    compose_dynamic_tree('invoice'),
    compose_dynamic_tree('expense'),

)

employee/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from address.models import *
from company.models import *
from erp_core.models import ErpAbstractBaseModel
from django.core.validators import MinValueValidator
from location.models import Office


class AddressForEmployee(Address):
    employee = models.OneToOneField(
        'Employee', on_delete=models.CASCADE, related_name="employee_address")
    landmark = models.CharField(max_length=255, blank=True, null=True)


class ContactForEmployee(Contact):
    employee = models.OneToOneField(
        'Employee', on_delete=models.CASCADE, related_name="employee_contact")


class Employee(ErpAbstractBaseModel):
    SEX = (
        ('Female', 'Female'),
        ('Male', 'Male'),
    )

    MARITALSTATUS = (
        ('Single', 'Single'),
        ('Married', 'Married'),
    )

    BLOODGROUP = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    )

    LICENSE = 'License'
    PASSPORT = 'Passport'
    IDPROOF = (
        (LICENSE, 'License'),
        (PASSPORT, 'Passport')
    )

    code = models.CharField(max_length=255, unique=True)
    photo = models.FileField(upload_to='prof/%Y/%m/%d', blank=True, null=True)
    dob = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=8, choices=SEX)
    status = models.BooleanField(default=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)

    primary_designation = models.ForeignKey(
        Designation, on_delete=models.CASCADE, null=True, blank=True)

    # secondary_designation = models.ManyToManyField(
    #     Designation, related_name="employee_secondary_designation", blank=True)

    reporting_officer = models.ForeignKey(
        'employee.Employee', on_delete=models.CASCADE, blank=True, null=True)

    id_proof_type = models.CharField(max_length=100, choices=IDPROOF, default=LICENSE, null=True, blank=True)
    id_proof_no = models.CharField(max_length=200, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])
    joining_date = models.DateField(null=True, blank=True)
    salary_date = models.DateField(null=True, blank=True)
    office = models.ForeignKey(Office, null=True, blank=False)

    class Meta:
        permissions = (
            ("view_employee_list", "Can view employee list"),
            ("view_employee_details", "Can view employee details"),
            ("can_access", "Can access Employee Section"),
            ("reporting_officier", "I am a reporting officier"),
            ("is_supervisor", "I am a supervisor"),
            ("view_report", "View report")
        )

    def get_absolute_url(self):
        return reverse('employee:profile', args=[self.code])

    def __str__(self):
        return str(self.user.first_name) + " (" + str(self.code) + ")"


class EmployeeCode(ErpAbstractBaseModel):
    character_set = models.CharField(max_length=100)

employee/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q, functions, Value as V
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from guardian.shortcuts import get_objects_for_user, assign_perm
from django.contrib import messages

from erp_core.pagination import paginate, cust_paginate
from .forms import *
from employee.filters import EmployeeFilter
from django.db.models import Sum, Count, F
from django.utils import timezone
from invoice.models import Invoice, InvoiceItem


@login_required
@permission_required('employee.can_access', raise_exception=True)
def index(request):
    f = EmployeeFilter(request.GET, queryset=get_objects_for_user(request.user, 'employee.view_employee_details',accept_global_perms=False))
    employees, pagination = paginate(request, queryset=f.qs, per_page=20, default=True)
    colors = ['.active','.success','.info','.warning','.danger']
    context = {
        'employees': employees,
        'pagination': pagination,
        'filter': f,
        'colors':colors,

    }
    return render(request, "employee/index.html", context)


@login_required
def select2_list(request):
    employee_name = request.GET.get('employee_name', False)
    if employee_name:
        employees = Employee.objects.filter(
            Q(user__username__icontains=employee_name) | Q(user__first_name__icontains=employee_name)
        ).annotate(
            text=functions.Concat('user__username', V(', '), 'primary_designation__name')
        ).values('id', 'text')
        return JsonResponse(list(employees), safe=False)
    return JsonResponse(list(), safe=False)

@login_required
def select_employee(request):
    employee_name = request.GET.get('employee_name', False)
    if employee_name:
        employees = Employee.objects.filter(
            user__first_name__contains=employee_name
        ).annotate(
            text=functions.Concat('user__first_name', V(', '), 'primary_designation__name')
        ).values('id', 'text')
        return JsonResponse(list(employees), safe=False)
    return JsonResponse(list(), safe=False)

@login_required
def select_designation(request):
    office_name = request.GET.get('office_name', False)
    if office_name:
        office = Office.objects.get(name=office_name)
        designations = Designation.objects.filter(office=office
                                                  ).annotate(
            text=('name')
        ).values('id', 'text')
        return JsonResponse(list(designations), safe=False)
    return JsonResponse(list(), safe=False)

@login_required
def select_office(request):
    offices = list(Office.objects.filter(name__contains=request.GET.get("office")).values('id', 'name').distinct())
    if request.is_ajax():
        return JsonResponse(offices, safe=False)


@login_required
@permission_required('employee.change_employee', raise_exception=True)
def create(request):
    form1 = UserForm(request.POST or None)
    form2 = EmployeeForm(request.POST or None, request.FILES or None)
    form3 = AddressForEmployeeForm(request.POST or None)
    form4 = ContactForEmployeeForm(request.POST or None)

    if request.method == "POST":

        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid():
            user = form1.save(commit=False)
            user.save()
            employee = form2.save(commit=False)
            employee.user = user
            employee.save()
            address = form3.save(commit=False)
            address.employee = employee
            address.save()
            contact = form4.save(commit=False)
            contact.employee = employee
            contact.save()
            form2.save_m2m()
            if employee.reporting_officer:
                # timesheet = TimeSheet.objects.update_or_create(employee=employee, approved_by=employee.reporting_officer)
                permission = Permission.objects.get(codename="reporting_officier")
                employee.reporting_officer.user.user_permissions.add(permission)
            if employee.primary_designation:
                for pr in employee.primary_designation.permissions.all():
                    employee.user.user_permissions.add(pr)

            messages.add_message(request, messages.INFO, 'Successfully Created')

            return HttpResponseRedirect(reverse('employee:profile', args=[employee.code]))

    context = {
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'form_url': reverse_lazy('employee:create')

    }

    return render(request, 'employee/create.html', context)



@login_required
def edit(request, pk):
    employee = get_object_or_404(Employee, code=pk)
    photo = employee.photo

    if request.method == "POST":
        form1 = UserEditForm(request.POST, instance=employee.user)
        form2 = EmployeeForm(request.POST, request.FILES, instance=employee)
        form3 = AddressForEmployeeForm(request.POST, instance=employee.employee_address)
        form4 = ContactForEmployeeForm(request.POST, instance=employee.employee_contact)

        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid():

            user = form1.save(commit=False)
            user.save()
            employee = form2.save(commit=False)
            employee.user = user
            if employee.photo == "":
                employee.photo = photo
            employee.save()
            address = form3.save(commit=False)
            address.employee = employee
            address.save()
            contact = form4.save(commit=False)
            contact.employee = employee
            contact.save()
            form2.save_m2m()
            messages.add_message(request, messages.SUCCESS, "Employer edited successfully")
            return HttpResponseRedirect(reverse('employee:profile', args=[employee.code]))

    else:

        form1 = UserEditForm(instance=employee.user)
        form2 = EmployeeForm(instance=employee)
        if employee.employee_address:
            form3 = AddressForEmployeeForm(instance=employee.employee_address)
        if employee.employee_contact:
            form4 = ContactForEmployeeForm(instance=employee.employee_contact)

    context = {

        'form1': form1,
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'edit': "edit",
        'employee':employee,
        'form_url': reverse_lazy('employee:edit', args=[employee.code])

    }

    return render(request, 'employee/create.html', context)


@login_required
@permission_required('employee.delete_employee', raise_exception=True)
def delete(request, pk):
    employee = get_object_or_404(Employee, code=pk)
    employee.user.delete()
    employee.delete()
    messages.add_message(request, messages.SUCCESS, "Employer deleted successfully")
    return HttpResponseRedirect(reverse('employee:list'))


@login_required
@permission_required('employee.can_access', raise_exception=True)
def profile(request, pk):
    employee = get_object_or_404(Employee, code=pk)
    return render(request, 'employee/profile.html', {'employee': employee})


@login_required
def employee_permission(request, pk):
    can_access = Permission.objects.get(codename="can_access")
    change_employee = Permission.objects.get(codename="change_employee")
    delete_employee = Permission.objects.get(codename="delete_employee")
    view_customer_list = Permission.objects.get(codename="view_customer_list")
    change_customer = Permission.objects.get(codename="change_customer")
    delete_customer = Permission.objects.get(codename="delete_customer")
    view_supplier_list = Permission.objects.get(codename="view_supplier_list")
    change_supplier = Permission.objects.get(codename="change_supplier")
    delete_supplier = Permission.objects.get(codename="delete_supplier")
    view_product_list = Permission.objects.get(codename="view_product_list")
    change_product = Permission.objects.get(codename="change_product")
    delete_product = Permission.objects.get(codename="delete_product")
    view_service_list = Permission.objects.get(codename="view_service_list")
    change_service = Permission.objects.get(codename="change_service")
    delete_service = Permission.objects.get(codename="delete_service")
    view_appointment_list = Permission.objects.get(codename="view_appointment_list")
    change_appointment = Permission.objects.get(codename="change_appointment")
    delete_appointment = Permission.objects.get(codename="delete_appointment")
    view_invoice_list = Permission.objects.get(codename="view_invoice_list")
    change_invoice = Permission.objects.get(codename="change_invoice")
    delete_invoice = Permission.objects.get(codename="delete_invoice")
    view_expense_list = Permission.objects.get(codename="view_expense_list")
    change_expense = Permission.objects.get(codename="change_expense")
    delete_expense = Permission.objects.get(codename="delete_expense")
    view_discount_list = Permission.objects.get(codename="view_discount_list")
    view_report = Permission.objects.get(codename="view_report")

    employee = get_object_or_404(Employee, pk=pk)
    if employee.user.has_perm('can_access'):
        emp_acc = True
    else:
        emp_acc = False

    if request.method == "POST":
        employee_permission = request.POST.get('permission')
        assign_perm('view_task', employee.user, employee)
        permission = Permission.objects.get(codename=employee_permission)
        # if permission in employee.user.user_permissions.all():
        #     employee.user.user_permissions.remove(permission)
        # else:
        #     employee.user.user_permissions.add(permission)
    # import guardian.templatetags.guardian_tags.get_obj_perms
    context = {
        'user': employee.user,
        'employee':employee,
        'emp_acc': emp_acc,

employee/templates/employee/index.html
{% extends "erp_admin/base.html" %} {% load guardian_tags util %}

{% block head %}
<style>


</style>
{% endblock %}
{% block content %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Filters</h4>
            </div>
            <div class="modal-body">
                <form action="" method="get">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ filter.form.code.label }}</label>
                            {{ filter.form.code }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ filter.form.name.label }}</label>
                            {{ filter.form.name }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ filter.form.designation.label }}</label>
                            {{ filter.form.designation }}
                        </div>
                    </div>


                    <div class="clearfix"></div>


                    <div class="col-sm-6">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="col-sm-6">
                <h2>Employees
                    <a href="{% url 'employee:create' %}" class="btn btn-link">
                        <i class="fa fa-plus-square-o fa-2x"></i>
                    </a>
                </h2>

            </div>
            <div class="col-sm-6">
                <a href="{% url 'employee:list' %}" class="btn btn-primary pull-right"> <i
                        class="fa fa-refresh"></i></a>
                <button type="button" class="btn btn-primary pull-right" data-toggle="modal"
                        data-target="#filter-modal"><i class="fa fa-search"></i>
                </button>

            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12 table-responsive" style="">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Mobile No.</th>
                        <th>Email</th>

                        {% if perms.employee.change_employee %}
                        <th colspan="3" align="center"></th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>

                    {% for employee in employees%}
                    <tr class={{col}}>
                        <td>{{ forloop.counter }}</td>
                        <td>

                            <a href="{% url 'employee:profile' employee.code %}">
                                {{employee}}
                            </a>
                        </td>
                        <td>
                            {{employee.employee_contact.phone}}
                        </td>
                        <td>
                            {{employee.user.email}}
                        </td>


                        {% if perms.employee.change_employee %}
                        <td>

                            <a href="{% url 'employee:edit' employee.code %}" class="pull-right">

                                <i class="fa fa-edit"></i>
                            </a>

                        </td>
                        {% endif %}
                        {% if perms.employee.delete_employee %}
                        <td>
                            <form class="delete" method="post" action="{% url 'employee:delete' employee.code %}">
                                {% csrf_token %}
                                <button type="submit" class="fabutton">
                                    <i class="fa fa-trash-o fa-fw"></i>
                                </button>
                            </form>

                        </td>
                        {% endif %}


                    </tr>

                    {% empty %}
                    <tr>
                        <td colspan="4">No Employees in System</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <div id="pagination" class="pull-right">
                    {{pagination|safe}}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}
{% block jsscript %}
<script>

$('form.delete').submit( function (e){
    e.preventDefault()
    e.stopPropagation()
    if(confirm('Are you sure?')){
        this.submit()
    }
})



</script>
{% endblock jsscript %}

employee/templates/employee/sales_by_employee.html
{% extends "erp_admin/base.html" %} {% load guardian_tags %}
{% load static %}

{% block head %}
<style>
.status-open {
    background-color:#afeeee;
    font-size:11px;
}
.status-rejected {
    background-color:#00bfff;
    font-size: 11px;
}
.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;

}
@media print {


  .sales{
    display:block!important;

  }
  }





</style>
{% endblock head %}

{% block content %}


<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="row">

                <div class="col-sm-9 col-md-9">
                    <h2>Sales By Employee</h2>
                    <h4>

                        {% if from_date == to_date %}
                        Date :
                        {{from_date}}
                        {% else %}
                        Duration :
                        {{from_date}} to {{to_date}}

                        {% endif %}
                    </h4>
                </div>
                <div class="col-sm-3 col-md-3">


                </div>

                <div class="row" style="padding: 16px;">
                    <form id="form" action="/employee/reports/salesbyemployee/" method="post">
                        {% csrf_token %}
                        <div class="col-sm-4">
                            <div id="date"
                                 style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%;">
                                <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                                <span>{% if from_date %}{{from_date}}-{{to_date}} {% else %} {{today|date:"F"}} {{today|date:"Y"}} {% endif %}</span><b
                                    class="caret"></b>
                            </div>
                        </div>
                        <input type="hidden" name="from" id="from" required>
                        <input type="hidden" name="to" id="to" required>

                        <div class="col-sm-3">
                            <button type="submit" class="btn btn-primary"> <i class="fa fa-search"></i></button>
                             <a href="{% url 'employee:sales_by_employee' %}" class="btn btn-primary"><i
                            class="fa fa-refresh"></i></a>
                        </a>
                        </div>

                    </form>
                </div>


            </div>
        </div>
        <div class="row show-grid" id="print_receipt">
            <div class="col-sm-12">
                <div style="display:none" class="sales">
                    <h2>Sales By Employee</h2>
                    <h4>

                        {% if from_date == to_date %}
                        Date :
                        {{from_date}}
                        {% else %}
                        Duration :
                        {{from_date}} to {{to_date}}

                        {% endif %}
                    </h4>
                </div>
                <div class="col-xs-14 col-sm-14 col-md-14">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="background-color: #f4f4f4!important;">
                            <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1"><h4>Total Services Done <i style="float:right;" class="fa fa-align-justify"></i></h4></a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="table-responsive">
                                <table class="table table-bordered servicetable">
                                    <thead>
                                    <tr>
                                        <th>Employee</th>
                                        <th>Total Number Of Services</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for invoice in totalservice %}
                                    <tr>
                                        <td class="employeename">{{ invoice.employee__user__first_name }}</td>
                                        <td>{{ invoice.tp}} </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="table-responsive">
                    <table class="table table-bordered servicetable">
                        <thead>
                        <tr>
                            <th>Employee</th>
                            <th>Type Of Service</th>
                            <th>Number Of Service</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in invoices %}
                        <tr>
                            <td class="employeename">{{ invoice.employee__user__first_name }}</td>
                            <td>{{ invoice.services__name}} </td>
                            <td>{{ invoice.tp}} </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="pagination">
                    {{ pagination|safe }}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script type="text/javascript">
  $("#form").submit(function(){

    from_val = $('#from').val();
    if (from_val==""){
      var url = "/employee/reports/salesbyemployee/";
    }
    else{
      var url = "/employee/reports/salesbyemployee/" + $('#from').val() + "/" + $('#to').val() + "/"; // get selected value
    }
    $("#form").attr("action", url);
  });

  $(document).ready(function() {

    function cb(start, end) {
      $('#date span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
      $("#from").val(start.format('YYYY-MM-DD'));
      $("#to").val(end.format('YYYY-MM-DD'));

    }

    $('#date').daterangepicker({
        //    startDate: start,
        // endDate: end,
      showDropdowns: true,
      locale: {
          format: 'YYYY-MM-DD',
        },
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);
      cb(start, end);

    });


</script>
{% endblock jsscript %}