bill/urls.py
from django.conf.urls import url, include
# from expense.bill.urls import urlpatterns as bill_patterns
from . import views

app_name = 'bill'

urlpatterns = [
    # url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^list/$', views.list, name='list'),
    url(r'^add/$', views.add_bill, name='add_bill'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit_bill, name='edit_bill'),
    url(r'^(?P<pk>[^/]+)/details/$', views.detail, name='detail'),

]

package/urls.py
from django.conf.urls import url
from package import views

app_name = "package"


urlpatterns = [
    url(r'^add/$', views.create, name='create'),
    url(r'^$', views.list, name='list'),
    url(r'^(?P<pk>[^/]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit, name='edit'),
    url(r'^buy/package/(?P<pk>[^/]+)/$', views.buy_package, name='buy_package'),
    url(r'^(?P<pk>[^/]+)/invoice_edit/$', views.edit_purchased_package, name='editpackage'),

]

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews
from rest_framework.authtoken import views

# from employee import views as employeeViews
from papercraneerp import allauth

urlpatterns = [
                  url(r'^$', erpAdminViews.dashboard),
                  url(r'^api-token-auth/', views.obtain_auth_token),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^accounts/password/change/$', allauth.login_after_password_change,
                      name='account_change_password'),  # Place before allauth urls to override
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^', include('employee.urls', namespace="employee")),
                  url(r'^', include('customer.urls', namespace="customer")),
                  url(r'^', include('product.urls', namespace="product")),
                  url(r'^chaining/', include('smart_selects.urls')),
                  url(r'^', include('service.urls', namespace="service")),
                  url(r'^', include('location.urls', namespace="location")),
                  url(r'^', include('invoice.urls', namespace="invoice")),
                  url(r'^', include('supplier.urls', namespace="supplier")),
                  url(r'^expense/', include('expense.urls', namespace="expense")),
                  url(r'^company/', include('company.urls', namespace="company")),
                  url(r'^vendor/', include('vendor.urls', namespace="vendor")),
                  url(r'^bill/', include('bill.urls', namespace="bill")),
                  url(r'^calendar/', include('calendarApp.urls', namespace="calendarApp")),
                  url(r'^discount/', include('discount.urls', namespace="discount")),
                  url(r'^package/', include('package.urls', namespace="package")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Saloon Administration'

register_dynamic_trees(
    compose_dynamic_tree('erp_admin'),
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('service'),
    compose_dynamic_tree('product'),
    compose_dynamic_tree('package'),
    compose_dynamic_tree('discount'),
    compose_dynamic_tree('supplier'),
    compose_dynamic_tree('vendor'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('calendarApp'),
    compose_dynamic_tree('invoice'),
    compose_dynamic_tree('expense'),

)

product/urls.py
from django.conf.urls import include, url
from product import api, views

app_name = "product"


urlpatterns = [
    url(r'^api/', include([
        # router.urls,
        url(r'^products/', include([
            url(r'^select_list/$', api.product_select_options, name="select_list"),
        ])),
        #get active products -api
        url(r'^products$', api.all_products, name="all_products"),

    ], namespace='api')),
    url(r'^product/add/$', views.add_products, name='add_products'),
    url(r'^products/$', views.view_products, name='view_products'),
    url(r'^product/(?P<pk>[^/]+)/$', views.detail, name='detail'),
    url(r'^product/(?P<product_pk>[^/]+)/edit/$',
        views.edit_product, name='edit_product'),
    url(r'^product/code/settings/$', views.code_settings, name='code_settings'),
    url(r'^product/(?P<pk>[^/]+)/delete/$', views.delete, name='delete'),
    url(r'^reports/salesbyproduct/$', views.sales_by_product, name='sales_by_product'),
    url(r'^reports/salesbyproduct/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', views.sales_by_product, name="sales_by_product"),



]

product/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from erp_core.models import BaseCodeSetting
from erp_core.models import ErpAbstractBaseModel
from invoice.models import InvoiceItem
from supplier.models import Supplier
from django.core.validators import MinValueValidator


class Category(ErpAbstractBaseModel):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)


class RawMaterialManager(models.Manager):
    def get_queryset(self):
        return super(RawMaterialManager, self).get_queryset().filter(raw_material=True)


class ConsumableManager(models.Manager):
    def get_queryset(self):
        return super(ConsumableManager, self).get_queryset().filter(consumable=True)


class Product(ErpAbstractBaseModel):
    objects = models.Manager()
    # raw_materials = RawMaterialManager()
    consumables = ConsumableManager()

    def newCode():
        return CodeSetting.new_code()

    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=30, unique=True, default=newCode)
    price = models.DecimalField("Selling Price", max_digits=20, decimal_places=2, null=True, blank=True,
                                validators=[MinValueValidator(0)])
    active = models.BooleanField(default=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True, blank=True, related_name="suppliers")
    invoice_products = GenericRelation(InvoiceItem, related_query_name='products')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.code and self.created_at is None:
            CodeSetting.incrementCountIndex()

        return super(Product, self).save(*args, **kwargs)

    class Meta:
        permissions = (
            ("view_product_list", "Can view product list"),

        )


class CodeSetting(BaseCodeSetting):
    pass

product/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product
from .models import CodeSetting


class ProductForm(ModelForm):
    class Meta:
        model = Product

        widgets = {

            "name": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            "code": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
            "price": forms.NumberInput(attrs={'class': "form-control", 'min': 0}),
            "supplier": forms.Select(attrs={'class': 'form-control', "multiple": False}),

        }
        fields = ['name', 'code', 'price', 'supplier']


class CodeSettingsForm(ModelForm):
    class Meta:
        model = CodeSetting

        widgets = {
            "prefix": forms.TextInput(attrs={'class': "form-control", 'id': "prefix", 'required': "required"}),
            "count_index": forms.TextInput(attrs={'class': "form-control", 'id': "count_index"}),
            "no_of_characters": forms.TextInput(attrs={'class': "form-control", 'id': "no_of_characters"}),
        }

        fields = ['prefix', 'count_index', 'no_of_characters']


# class PackageForm(ModelForm):
#     class Meta:
#         model = Product
#
#         widgets = {
#
#             "name": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
#             "code": forms.TextInput(attrs={'class': "form-control", 'required': "required"}),
#             "price": forms.NumberInput(attrs={'class': "form-control", 'min': 0}),
#             "validity_days": forms.NumberInput(attrs={'class': "form-control", 'required': "required", 'min': 0}),
#             "minimum_purchase_amount": forms.NumberInput(attrs={'class': "form-control", 'required': "required", 'min': 0}),
#
#         }
#         fields = ['name', 'code', 'price', 'validity_days', 'minimum_purchase_amount']

product/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.db.models import Sum

from .forms import *
from erp_core.pagination import paginate
from .filters import ProductFilter
from invoice.models import InvoiceItem
from django.contrib import messages

# Add The Products

@login_required
@permission_required('product.change_product', raise_exception=True)
def add_products(request):
    form = ProductForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            product = form.save(commit=False)
            product.consumable = True
            product.save()
            form.save_m2m()
            messages.add_message(request, messages.SUCCESS, "Product added successfully")
            return HttpResponseRedirect(reverse('product:view_products'))
    context = {
        "form": form,
        'form_url': reverse_lazy('product:add_products'),
        "type": "Create"
    }
    return render(request, 'product/add_products.html', context)

# Details the Products

@login_required
@permission_required('product.view_product_list', raise_exception=True)
def view_products(request):

    f = ProductFilter(request.GET, queryset=Product.objects.all().order_by("-created_at"))

    # products = Product.objects.all().order_by("-created_at")
    products, pagination = paginate(request, queryset=f.qs, per_page=10, default=True)
    # for page in pagination:
    #     print(page)
    context = {
        "products": products,
        'pagination': pagination,
        'filter': f,
    }
    return render(request, 'product/view_products.html', context)

@login_required
@permission_required('product.view_product_list', raise_exception=True)
def detail(request, pk):
    product = Product.objects.get(id=pk)
    context = {
        "product": product,
        "pk": pk
    }
    return render(request, "product/detail.html", context)

@login_required
@permission_required('product.change_product', raise_exception=True)
def edit_product(request, product_pk):

    product = Product.objects.get(id=product_pk)
    form = ProductForm(
        request.POST or None, instance=product)

    if request.method == "POST":
        form.save()
        messages.add_message(request, messages.SUCCESS, "Product edited successfully")
        return HttpResponseRedirect(reverse('product:view_products'))
    context = {
        "form": form,
        'form_url': reverse_lazy('product:edit_product', args=[product_pk]),
        "product_pk": product_pk,
        "type": "Edit",
        'product':product,
    }
    return render(request, 'product/add_products.html', context)


def code_settings(request):
    if CodeSetting.objects.exists():
        code_form = CodeSettingsForm(request.POST or None, instance=CodeSetting.objects.last())
    else:
        code_form = CodeSettingsForm(request.POST or None)

    if request.method == "POST":
        if code_form.is_valid():
            code_form.save()
            messages.add_message(request, messages.SUCCESS, "Successfully created code format")
            return HttpResponseRedirect(reverse('product:view_products'))

    context = {
        'code_form': code_form,
    }

    return render(request, "product/code_setting.html", context)

@login_required
@permission_required('product.delete_product', raise_exception=True)
def delete(request, pk):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        messages.add_message(request, messages.SUCCESS, "Product deleted successfully")
        return HttpResponseRedirect(reverse('product:view_products'))

@login_required
@permission_required('employee.view_report', raise_exception=True)
def sales_by_product(request,from_date=None,to_date=None):
    if not from_date:
        from_date = timezone.now().date()
        to_date = timezone.now().date()
    products = InvoiceItem.objects.filter(invoice__created_at__date__range=[from_date, to_date],
                                          content_type__model='product').values('products__name').annotate(
        quantity=Sum('hours_or_sqfeet'), total_cp=Sum('total_price'))
    context = {
        'from_date': from_date,
        'to_date': to_date,
        'products': products
    }
    return render(request, "product/sales_by_product.html",context)

product/templates/product/add_products.html
{% extends "erp_admin/base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}"/>

{% endblock head %}
{% block content %}

<div class="banner">
    <h2>
        <a href="{% url 'product:view_products' %}">Products</a>
        <i class="fa fa-angle-right"></i>
        <span>{{type}}</span>
        <a href="{{ request.META.HTTP_REFERER }}"><i class="fa fa-times pull-right" aria-hidden="true"></i></a>

    </h2>
</div>

<div class="blank">
    <div class="grid-form1">
        <div class="tab-content">
            <div class="tab-pane active" id="horizontal-form">
                <form class="form-horizontal" action="{{ form_url }}" method="post">{% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label col-xs-12">
                            {{ field.label }}
                            {% if field.form.use_required_attribute %}
                                <span class="req">*</span>
                            {% endif %}
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% if field.label == "supplier" %}
                            <a href="{% url 'supplier:create' %}" style="font-size: 0.8em;" target="_blank">Add</a>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-8">
                            <button class="btn-primary btn">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block jsscript %}

<script src="{% static 'js/select2.min.js' %}"></script>

<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>

<script>
      $(document).ready(function() {
        $('.tdate').daterangepicker({
          singleDatePicker: true,
          // calender_style: "picker_4",
          showDropdowns: true,
          minDate:new Date(),
          locale: {
        		format: 'YYYY-MM-DD',
      			},

        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });
      });


</script>

<script>
	
	$("#tax").select2({
		maximumSelectionLength: 10,
		allowClear: true,
		
		});



</script>

<script>
// $(document).ready(function() {
//     var subtask_input = $("#id_sub_task");
//     var subtask = subtask_input.select2({
//       ajax: {
//         url: "/select_list/",
//         dataType: 'json',
//         delay: 250,
//         data: function (params) {
//           return {
//             subtask_code: params.term, // search term
//           };
//         },
//         processResults: function (data) {
//           // parse the results into the format expected by Select2
//           // since we are using custom formatting functions we do not need to
//           // alter the remote JSON data, except to indicate that infinite
//           // scrolling can be used
//           console.log(data);
//           return {
//             results: data,
//           };
//         },
//         cache: true
//       },
//       escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
//       minimumInputLength: 3,
//       // templateResult: formatRepo, // omitted for brevity, see the source of this page
//       // templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
//     });
    
// });


</script>
{% endblock jsscript %}

product/templates/product/code_setting.html
{% extends "erp_admin/base.html" %}
{% load static %} 
{% block content %}

<div class="blank">
	 <div class="grid-form1">
	 	  <a href="{% url 'product:add_products' %}">Cancel</a>
  	       <h3 style="margin-top:20px;">Prefix</h3>
  	         <div class="tab-content">
						<div class="tab-pane active" id="horizontal-form">
							<form class="form-horizontal" id="code_setting" action="{% url 'product:code_settings' %}" method="post">{% csrf_token %}
							{{ code_form.non_field_errors }}
							{{ code_form.field_errors }}
							
								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Prefix</label>
									<div class="col-sm-8 code-input">{{ code_form.prefix.errors }}
										{{ code_form.prefix }}
									</div>
								</div>

								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Count</label>
									<div class="col-sm-8 code-input">{{ code_form.count_index.errors }}
										{{ code_form.count_index }}
									</div>
								</div>
								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Number Of Characters</label>
									<div class="col-sm-8 code-input">{{ code_form.no_of_characters.errors }}
										{{ code_form.no_of_characters }}
									</div>
								</div>
								<div class="form-group">
									<label for="subject" class="col-sm-2 control-label">Stock Code:</label>
									<div class="col-sm-8 code-input">
										<span id="code"></span>
									</div>
									
								</div>
								

								<div class="form-group">
									<div class="col-sm-8">
                						<button class="btn-primary btn">Submit</button>
                					</div>
                				</div>

								
							</form>
						</div>
					</div>
					
	</div>
</div>
{% endblock content %}
{% block jsscript %}
<script>
$(document).ready(function(){
	$("form#code_setting").on('input', function(e){
		var code = ""
		var prefix = $(this).find("#prefix").val()
		// console.log(prefix)
		if(prefix){
			code += prefix
			
			var no_of_characters = $(this).find("#no_of_characters").val()
			var count = $(this).find("#count_index").val() + ""
			
			function pad(num, size) {
			    var s = num+"";
			    while (s.length < size) s = "0" + s;
			    return s;
			}
			
			code += pad(count, no_of_characters)
			
			console.log(code)
		}
		$("#code").text(code)
	})
	$("form#code_setting").trigger('input')
})	
</script>



{% endblock jsscript %}

product/templates/product/sales_by_product.html
{% extends "erp_admin/base.html" %}
{% load static %}

{% block head %}
<style>

.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;
    
}
@media print {

  
  .sales{
    display:block!important;

  }
  }


</style>
{% endblock head %}

{% block content %}


<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="row">

                <div class="col-sm-9 col-md-9">
                    <h2>Sales By Product</h2>
                    <h4>

                        {% if from_date == to_date %}
                        Date :
                        {{from_date}}
                        {% else %}
                        Duration :
                        {{from_date}} to {{to_date}}

                        {% endif %}
                    </h4>
                </div>
                <div class="col-sm-3 col-md-3">

                </div>

                <div class="row" style="padding: 16px;">
                    <form id="form" action="/reports/salesbyproduct/" method="post">
                        {% csrf_token %}
                        <div class="col-sm-4">
                            <div id="date"
                                 style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%;">
                                <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                                <span>{% if from_date %}{{from_date}}-{{to_date}} {% else %} {{today|date:"F"}} {{today|date:"Y"}} {% endif %}</span><b
                                    class="caret"></b>
                            </div>
                        </div>
                        <input type="hidden" name="from" id="from" required>
                        <input type="hidden" name="to" id="to" required>

                        <div class="col-sm-3">
                            <button type="submit" class="btn btn-primary"> <i class="fa fa-search"></i></button>
                            <a onclick="printDiv()" class="btn btn-primary" target="__blank"> <i class="fa fa-print fa-fw"></i>
                        </a>
                    <a href="{% url 'product:sales_by_product' %}" class="btn btn-primary"><i
                            class="fa fa-refresh"></i></a>
                        </div>

                    </form>
                </div>


            </div>
        </div>
        <div class="row show-grid" id="print_receipt">
            <div class="col-sm-12">
                <div style="display:none" class="sales">
                    <h2>Sales By Product</h2>
                    <h4>

                        {% if from_date == to_date %}
                        Date :
                        {{from_date}}
                        {% else %}
                        Duration :
                        {{from_date}} to {{to_date}}

                        {% endif %}
                    </h4>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>

                        <tr>
                            <th>Product</th>
                            <th>Sold Quantity</th>
                            <th>Total Cost Price</th>


                        </tr>
                        </thead>
                        <tbody>
                        {% for product in products %}

                        <tr>
                            <td>{{product.products__name}}</td>
                            <td>{{product.quantity}}</td>
                            <td>{{product.total_cp}}</td>

                        </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                </div>
                <div id="pagination">
                    {{ pagination|safe }}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script type="text/javascript">
      //  var a = document.getElementById('linkId'); //or grab it by tagname etc
      //  var d = new Date();
  // // d.getMonth();
      // //   var from_date =
      //  a.href = "/reports/salesbycustomer/"
  $("#form").submit(function(){
  
    from_val = $('#from').val();
    if (from_val==""){
      var url = "/reports/salesbyproduct/";
    }
    else{
      var url = "/reports/salesbyproduct/" + $('#from').val() + "/" + $('#to').val() + "/"; // get selected value
    }
    $("#form").attr("action", url);
  });
  
  $(document).ready(function() {
    // var start = moment().subtract(29, 'days');
    //    var end = moment();
    function cb(start, end) {
      $('#date span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
      $("#from").val(start.format('YYYY-MM-DD'));
      $("#to").val(end.format('YYYY-MM-DD'));
    
    }
  
    $('#date').daterangepicker({
        //    startDate: start,
        // endDate: end,
      showDropdowns: true,
      locale: {
          format: 'YYYY-MM-DD',
        },
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);
      cb(start, end);
    
    });

</script>
<script>

    function printDiv() {    

    var printContents = document.getElementById('print_receipt').innerHTML;
    var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
    }

</script>
{% endblock jsscript %}

product/templates/product/view_products.html
{% extends "erp_admin/base.html" %}
{% load static %}
{% block content %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Filters</h4>
            </div>
            <div class="modal-body">
                <form action="" method="get">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ filter.form.code.label }}</label>
                            {{ filter.form.code }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">{{ filter.form.name.label }}</label>
                            {{ filter.form.name }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Price</label>
                            {{ filter.form.price }}
                        </div>
                    </div>


                    <div class="clearfix"></div>


                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="blank">
    <div class="blank-page">
        <div class="row show-grid">
            <div class="col-sm-6 col-md-6 col-xs-12">
                <h2>Products
                    <a href="{% url 'product:add_products' %}" class="btn btn-link">
                        <i class="fa fa-plus-square-o fa-2x"></i>
                    </a>
                </h2>
            </div>

        </div>
        <div class="row">
            <div class="pull-right">

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#filter-modal">
                    <i class="fa fa-search"></i>
                </button>
                <a href="{% url 'product:view_products' %}" class="btn btn-primary"> <i
                        class="fa fa-refresh"></i></a>
                <a href="{% url 'product:code_settings' %}" class="btn btn-primary">
                    <i class="fa fa fa-cog"></i>
                </a>
            </div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12">
                <div class="table-responsive">

                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Price(AED)</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in products %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a href="{% url 'product:detail' product.pk %}">{{product.name }}</a>
                            </td>
                            <td>{{ product.code }}</td>
                            <td>{{product.price }}</td>

                            <td>
                                <a href="{% url 'product:edit_product' product.pk %}"><i class="fa fa-edit"></i></a>
                            </td>
                            <td>
                                <form class="delete" method="post" action="{% url 'product:delete' product.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="fabutton">
                                        <i class="fa fa-trash-o fa-fw"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>

                        {% empty %}
                        <tr>
                            <td colspan="7">No Products</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="pagination">
                {{ pagination|safe }}
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block jsscript %}

<script>
$('form.delete').submit( function (e){
    e.preventDefault()
    e.stopPropagation()
    if(confirm('Are you sure?')){
        this.submit()
    }
})

</script>

{% endblock jsscript %}