bill/urls.py
from django.conf.urls import url, include
# from expense.bill.urls import urlpatterns as bill_patterns
from . import views

app_name = 'bill'

urlpatterns = [
    # url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^list/$', views.list, name='list'),
    url(r'^add/$', views.add_bill, name='add_bill'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit_bill, name='edit_bill'),
    url(r'^(?P<pk>[^/]+)/details/$', views.detail, name='detail'),

]

expense/bill/urls.py
from django.conf.urls import include, url
from . import views, receipt


urlpatterns = [
    url(r'^$', views.index, name="list"),
    url(r'^pre_create/$', views.pre_create, name="pre-create"),
    url(r'^create/(?P<payee_type>[^/]+)/(?P<order_type>[^/]+)/$', views.create, name="create"),

    url(r'^code/settings/$', views.code_settings, name='code_settings'),

    url(r'^(?P<bill_pk>[^/]+)/', include([
        url(r'^edit/$', views.edit, name="edit"),
        url(r'^delete/$', views.delete, name="delete"),
        url(r'^add_payment_term/$', views.add_payment_terms, name='add-payment-terms'),
        url(r'^$', views.detail, name='detail'),
    ])),

    # url(r'^(?P<payee_type>[^/]+)/(?P<order_type>[^/]+)/$', views.index, name="filtered-list"),
    url(r'^payment_term/(?P<bill_payment_term_pk>[^/]+)/', include([
        url(r'^delete/$', views.delete_payment_term, name="delete"),

        url(r'^receipts/', include([
            url(r"^$", receipt.index, name="list"),
            url(r"^add/$", receipt.create, name="create"),
            url(r'^(?P<receipt_pk>[^/]+)/', include([
                url(r"download/$", receipt.download, name="download"),
                url(r"^edit/$", receipt.edit, name="edit"),
                url(r"^delete/$", receipt.delete, name="delete"),
            ])),
        ], namespace="receipt")),
    ], namespace='payment_term'))
]

expense/urls.py
from django.conf.urls import url, include
from expense.bill.urls import urlpatterns as bill_patterns
from . import views

app_name = 'expense'

urlpatterns = [
    url(r'^(?P<pk>[^/]+)/detail/$', views.detail, name='detail'),
    url(r'^bills/', include(bill_patterns, namespace="bill")),
    url(r'^recordExpense/create/(?P<payee_type>[\w-]+)/$', views.record_expense_create, name='record_expense_create'),
    url(r'^bulkAddExpense/create/(?P<payee_type>[\w-]+)/$', views.bulk_expense_create, name='bulk_expense_create'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[^/]+)/details/$', views.view_expense, name='view_expense'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit_Expense, name='edit_Expense'),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^expense_type_list/$', views.expense_type_list, name='expense_type_list'),
    url(r'^(?P<pk>[^/]+)/delete/$', views.delete, name="delete"),
    url(r'^supplier_or_vendor/$', views.supplier_or_vendor, name="supplier_or_vendor"),
    url(r'^supplier_or_vendor/bulk_create/$', views.supplier_or_vendor, {'bulk': True}, name="bulk_supplier_or_vendor"),
]

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews
from rest_framework.authtoken import views

# from employee import views as employeeViews
from papercraneerp import allauth

urlpatterns = [
                  url(r'^$', erpAdminViews.dashboard),
                  url(r'^api-token-auth/', views.obtain_auth_token),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^accounts/password/change/$', allauth.login_after_password_change,
                      name='account_change_password'),  # Place before allauth urls to override
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^', include('employee.urls', namespace="employee")),
                  url(r'^', include('customer.urls', namespace="customer")),
                  url(r'^', include('product.urls', namespace="product")),
                  url(r'^chaining/', include('smart_selects.urls')),
                  url(r'^', include('service.urls', namespace="service")),
                  url(r'^', include('location.urls', namespace="location")),
                  url(r'^', include('invoice.urls', namespace="invoice")),
                  url(r'^', include('supplier.urls', namespace="supplier")),
                  url(r'^expense/', include('expense.urls', namespace="expense")),
                  url(r'^company/', include('company.urls', namespace="company")),
                  url(r'^vendor/', include('vendor.urls', namespace="vendor")),
                  url(r'^bill/', include('bill.urls', namespace="bill")),
                  url(r'^calendar/', include('calendarApp.urls', namespace="calendarApp")),
                  url(r'^discount/', include('discount.urls', namespace="discount")),
                  url(r'^package/', include('package.urls', namespace="package")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Saloon Administration'

register_dynamic_trees(
    compose_dynamic_tree('erp_admin'),
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('service'),
    compose_dynamic_tree('product'),
    compose_dynamic_tree('package'),
    compose_dynamic_tree('discount'),
    compose_dynamic_tree('supplier'),
    compose_dynamic_tree('vendor'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('calendarApp'),
    compose_dynamic_tree('invoice'),
    compose_dynamic_tree('expense'),

)

expense/bill/forms.py
from django.contrib.contenttypes.models import ContentType
from django.forms import BaseInlineFormSet, ValidationError
from django.apps import apps
from django import forms

from .models import Bill, CodeSetting, BillReceipt, ORDER_TYPES, PAYEE_TYPES
from supplier.models import Supplier
# from raw_material.purchase_order.models import PurchaseOrder

from django.forms import ModelChoiceField


class PreBillForm(forms.Form):

    order_type = forms.ChoiceField(
        choices=ORDER_TYPES,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    payee_type = forms.ChoiceField(
        choices=PAYEE_TYPES,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )


class BillForm(forms.ModelForm):

    class Meta:
        model = Bill
        widgets = {
            "code": forms.TextInput(attrs={'class': "form-control", 'id': "code"}),
            # "order_number": forms.TextInput(attrs={'class': "form-control", 'id': "order_number"}),
            "tax": forms.NumberInput(attrs={'class': "form-control", 'id': "tax", 'required': "required"}),
            "tax_inclusive": forms.CheckboxInput(attrs={'id': "tax_inclusive"}),
            "amount": forms.NumberInput(
                attrs={'class': "form-control", 'id': "amount", 'required': "required"}),
            "created_by": forms.Select(
                attrs={'class': "form-control", 'id': "sales_person", 'required': "required"}),
            # "payment_terms": forms.SelectMultiple(attrs={'class': "form-control", "data-toggle": "select", "id": "payment_terms",  'multiple': "multiple",'required': "required"}),
            "billed_date": forms.DateInput(
                attrs={'class': "form-control", 'required': "required", 'type': "text", 'id': "billed_date"}),
            "due_date": forms.DateInput(
                attrs={'class': "form-control", 'required': "required", 'type': "text", 'id': "due_date"}),
        }
        fields = ['code', 'tax', 'amount', 'due_date', 'billed_date', 'tax_inclusive']


class PayeeForm(forms.Form):
    payee = forms.ModelChoiceField(
        queryset=Supplier.objects.none(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    def __init__(self, *args, **kwargs):
        payee_type = kwargs.pop('payee_type')
        z = ContentType.objects.get(model=payee_type)
        PayedTo = apps.get_model(z.app_label, payee_type)
        queryset = PayedTo.objects.all()
        super(PayeeForm, self).__init__(*args, **kwargs)
        self.fields['payee'].queryset = queryset
    

# class OrderForm(forms.Form):
#     order = forms.ModelChoiceField(
#         queryset=PurchaseOrder.objects.none(),
#         # required=True,
#         widget=forms.Select(attrs={'class': 'form-control'}),
#     )
#
#     def __init__(self, *args, **kwargs):
#         order_type = kwargs.pop('order_type')
#         # z = ContentType.objects.get(model=order_type)
#         OrderClass = apps.get_model(order_type)
#         queryset = OrderClass.objects.all()
#         super(OrderForm, self).__init__(*args, **kwargs)
#         self.fields['order'].queryset = queryset


class CodeSettingForm(forms.ModelForm):

    class Meta:
        model = CodeSetting

        widgets = {
            "prefix": forms.TextInput(
                attrs={'class': "form-control", 'id': "prefix", 'required': "required"}),
            "count_index": forms.TextInput(
                attrs={'class': "form-control", 'id': "count_index"}),
            "no_of_characters": forms.TextInput(
                attrs={'class': "form-control", 'id': "no_of_characters"}),
        }

        fields = ['prefix', 'count_index', 'no_of_characters']


class BillReceiptForm(forms.ModelForm):

    class Meta:
        model = BillReceipt
        widgets = {
            "code": forms.TextInput(attrs={'class': "form-control", 'id': "code"}),
            "amount": forms.NumberInput(
                attrs={'class': "form-control", 'id': "amount", 'required': "required"}),
            "received_date": forms.DateInput(
                attrs={'class': "form-control received_date", 'type': "text"}),
        }
        fields = ['amount', 'document', 'code', 'received_date', 'code']


class CustomInlineFormset(BaseInlineFormSet):
    def clean(self):
        super(CustomInlineFormset, self).clean()
        # example custom validation across forms in the formset
        # amount = 0
        # for form in self.forms:
        #     amount += form.cleaned_data['amount']
        #     if amount >  self.instance.amount:
        #         raise ValidationError("The sum of all the receipts is greater than payment term amount")

        # your custom formset validation

expense/bill/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.utils import timezone
from django.db import transaction
from erp_core.pagination import paginate
from .filters import BillFilter
from .forms import BillForm, CodeSettingForm, PayeeForm, PreBillForm
from .models import Bill, CodeSetting, BillPaymentTerm, PAYEE_TYPES
# from supplier.models import SupplierContact
from decimal import Decimal
from django.forms import modelform_factory
from erp_core.models import PaymentTerm

# Create your views here.


def index(request, payee_type=None, order_type=None):
    f = BillFilter(request.GET, request=request)
    bills, pagination = paginate(request, queryset=f.qs, per_page=5, default=True)
    context = {
        'bills': bills,
        'payee_types': PAYEE_TYPES,
        'pagination': pagination,
        'filter': f,
    }
    return render(request, "bills/list.html", context)


@transaction.atomic
def pre_create(request):

    form = PreBillForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            order_type = form.cleaned_data['order_type']
            payee_type = form.cleaned_data['payee_type']
            return redirect(reverse("expense:bill:create", args=[payee_type, order_type]))

    context = {
        'form': form,
        'form_url': reverse('expense:bill:pre-create'),
    }
    return render(request, "bill/pre_create.html", context)


@transaction.atomic
def create(request, payee_type, order_type):

    payee_form = PayeeForm(request.POST or None, payee_type=payee_type)
    # order_form = OrderForm(request.POST or None, order_type=order_type)
    bill_form = BillForm(request.POST or None, request.FILES or None)
    payment_terms = PaymentTerm.objects.all()

    if request.method == 'POST':
        if bill_form.is_valid() and payee_form.is_valid():

            bill = bill_form.save(commit=False)
            bill.payee = payee_form.cleaned_data['payee']
            bill.order = order_form.cleaned_data['order']
            bill.save()
            bill.add_payment_terms(request.POST.getlist('payment', []))

            return redirect(reverse("expense:bill:detail", args=[bill.id]))

    context = {
        'bill_form': bill_form,
        'payee_form': payee_form,
        # 'order_form': order_form,
        'payment_terms': payment_terms,
        # 'invoice_shipping_address_form': invoice_shipping_address_form,
        'form_url': reverse('expense:bill:create', args=[payee_type, order_type]),
    }
    return render(request, "bill/edit.html", context)


def detail(request, bill_pk):
    bill = Bill.objects.get(pk=bill_pk)
    context = {
        'bill': bill,
    }
    return render(request, "bill/detail.html", context)


@transaction.atomic
def edit(request, bill_pk):
    bill = get_object_or_404(Bill, pk=bill_pk)
    if bill.status == bill.PAID:
        messages.add_message(request, messages.WARNING, 'Editing is not possible since the bill is already paid')
        return redirect(reverse('expense:bill:detail', args=[bill_pk]))

    Form = modelform_factory(Bill, form=BillForm, exclude=['code'])
    bill_form = Form(request.POST or None, request.FILES or None, instance=bill)

    payment_terms = PaymentTerm.objects.all()

    if request.method == 'POST':
        if bill_form.is_valid():

            bill = bill_form.save(commit=False)
            bill.save()
            bill.add_payment_terms(request.POST.getlist('payment', False))
            return redirect(reverse("expense:bill:detail", args=[bill_pk]))
    context = {
        'bill_form': bill_form,
        'bill': bill,
        'payment_terms': payment_terms,
        # 'invoice_shipping_address_form': invoice_shipping_address_form,
        'form_url': reverse('expense:bill:edit', args=[bill_pk]),
        'edit': 'edit',
    }
    return render(request, "bill/edit.html", context)


@transaction.atomic
def code_settings(request):

    if CodeSetting.objects.exists():
        code_form = CodeSettingForm(request.POST or None, instance=CodeSetting.objects.last())
    else:
        code_form = CodeSettingForm(request.POST or None)
    if request.method == "POST":
        if code_form.is_valid():
            code_settings = code_form.save()
            messages.add_message(request, messages.SUCCESS, "Successfully created code format")
            return redirect(reverse('expense:bill:list'))
    context = {
        'code_form': code_form,
    }

    return render(request, "bill/code_setting.html", context)


@transaction.atomic
def delete(request, bill_pk):
    bill = get_object_or_404(Bill, pk=bill_pk)

    if bill.status == bill.PAID:
        messages.add_message(request, messages.WARNING, 'Deletion is not possible')
        return redirect(reverse('expense:bill:detail', args=[bill_pk]))

    bill.delete()
    return redirect(reverse('expense:bill:list'))


@transaction.atomic
def add_payment_terms(request, bill_pk):
    bill = get_object_or_404(Bill, pk=bill_pk)
    payment_term_id_list = [pt.id for pt in bill.payment_terms.all()]
    payment_terms = PaymentTerm.objects.exclude(id__in=payment_term_id_list).all()

    if request.method == 'POST':
        bill.add_payment_terms(request.POST.getlist('payment', False))
        return redirect(reverse('expense:bill:detail', args=[bill_pk]))

    context = {
        'payment_terms': payment_terms,
        'bill': bill,
        'form_url': reverse('expense:bill:add-payment-terms', args=[bill_pk]),
    }
    return render(request, "bill/add_payment_terms.html", context)


@transaction.atomic
def delete_payment_term(request, bill_payment_term_pk):

    bill_payment_term = get_object_or_404(BillPaymentTerm, pk=bill_payment_term_pk)

    if bill_payment_term.status == BillPaymentTerm.NOT_PAID:
        bill_payment_term.delete()
    else:
        messages.add_message(request, messages.WARNING, 'Deletion is not Possible')
    return redirect(reverse('expense:bill:detail', args=[bill_payment_term.bill.pk]))

expense/templates/expense/list.html
{% extends "erp_admin/base.html" %}{% load humanize %}
{% load static %}
{% block head %}
<style type="text/css">
.status-notpaid {
    background-color: red;
    font-size: 12px;
}
.status-paid {
    background-color: #2fd22f;
    font-size: 12px;
}

.fabutton {
  background: none;
  padding: 0px;
  border: none;
}
.table>thead>tr>th{
    color: #00ABE7!important;
    font-size: 15px!important;   
}
</style>
{% endblock head %}
{% block content %}

<!-- Modal -->

<div class="banner">
    <h2>
        <a href="{% url 'expense:dashboard' %}">Dashboard</a>
        <i class="fa fa-angle-right"></i>
        <span>List</span>
        <a href="{{ request.META.HTTP_REFERER }}"><i class="fa fa-times pull-right" aria-hidden="true"></i></a>
    </h2>
</div>

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Filters</h4>
      </div>
      <div class="modal-body">
        <form action="" method="get">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.expense_type.label }}</label>
                        {{ filter.form.expense_type }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.amount.label }}</label>
                        {{ filter.form.amount }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.payee_type.label }}</label> {{ filter.form.payee_type }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.payee_name.label }}</label> {{ filter.form.payee_name }}
                    </div>
                </div>
            </div>
            
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.customer.label }}</label>
                        {{ filter.form.customer }}
                    </div>
                </div>               
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.paid.label }}</label>
                        {{ filter.form.paid }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.created_at.label }}</label>
                        {{ filter.form.created_at }}
                        <div id="created_at" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%;">
                            <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                            <span>{% if from_date %}{{from_date}}-{{to_date}} {% else %} {{today|date:"F"}} {{today|date:"Y"}} {% endif %}</span><b class="caret"></b>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="row">
                <h4 style="padding: 10px;">Sort By</h4>
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="control-label">{{ filter.form.order_by_amount.label }}</label>
                        {{ filter.form.order_by_amount }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="pull-left" style="padding-left:10px;">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="clearfix"></div>

            </div>

        </form>
      </div>
    </div>
  </div>
</div>


    <div class="content-main">
        <div class="block">
            <div class="row">

            </div>
            <div class="row show-grid">
                <div class="col-sm-6">
                    <h3>
                        Expenses
                        <a href="{% url 'expense:supplier_or_vendor' %}" class="btn btn-link">
                              <i class="fa fa-plus-square-o fa-2x"></i>
                        </a>
                    </h3>
                </div>
                <div class="col-sm-6">
                    <div class="pull-right">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#filter-modal">
                          <i class="fa fa-filter"></i>
                        </button>
                        <a class="btn btn-primary btn-sm" href="{% url 'expense:index' %}">
                         <i class="fa fa-refresh"></i>
                        </a>
                    </div>
                </div>                         
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>Vendor/Supplier</th>
                                    <th>Amount</th>
                                    <th>Status</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for expense in expenses %}
                                <tr>
                                    <td scope="row">{{ forloop.counter }}</td>
                                    <td>{{ expense.date }}</td>

                                    <td>
                                        <a href="{% url 'expense:view_expense' expense.pk %}"> 
                                            {{ expense.expense_type }}
                                        </a>

                                    </td>
                                    
                                    <td>{{expense.payee}}</td>
                                    <td>
                                        <i class="fa fa-inr"></i> {{ expense.amount }}
                                    </td>
                                    <td>
                                        {% if expense.paid %}
                                            <span class="label status status-paid">PAID</span>
                                        {% else %}
                                            <span class="label status status-notpaid">NOT PAID</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                       
                                        <a href="{% url 'expense:edit_Expense' expense.pk %}">
                                            <i class="fa fa-edit fa-1x"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <form method="post" class="delete" action="{% url 'expense:delete' expense.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" class="fabutton">
                                                <i class="fa fa-trash-o fa-fw"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>No Expenses</tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <div id="pagination">
                        {{pagination|safe}}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block jsscript %}
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script>

$('form.delete').submit( function (e){
    e.preventDefault()
    e.stopPropagation()
    if(confirm('Are you sure?')){
        this.submit()
    }
})

$(document).ready(function(){
    $('.tdate').daterangepicker({
          singleDatePicker: true,
          // timePicker: true,
          // calender_style: "picker_4",
          showDropdowns: true,
          locale: {
                format: 'YYYY-MM-DD',
                },


        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
    });
    $('[data-toggle="tooltip"]').tooltip();

    $("#pagination a").click(function(e){
        e.preventDefault()
        page_string = this.href.slice(this.href.indexOf("?") + 1)
        
        var query_string = ""   
        var search_query = window.location.search
        var query_obj = {}
        if(search_query){
            if(search_query.indexOf('?') > -1)
                search_query = search_query.substr(1)
            
            var searchQueryStrings = [search_query]
            if(search_query.indexOf('&') > -1)
                searchQueryStrings = search_query.split('&')
            
            searchQueryStrings.forEach(qs => {
                var query_array = qs.split('=')
                query_obj[query_array[0]] = query_array[1]
            })

        }
        
        query_obj['page'] = page_string.split('=')[1]
        for(var k in query_obj){
            query_string += k + '=' + query_obj[k] + '&'
        }
        
        // console.log(query_string, query_obj, window.location)
        window.location = window.location.pathname + "?" + query_string.slice(0, -1)
    })
    var format = 'YYYY-MM-DD H:mm'
    function cb(start, end) {
        $('#created_at span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $("#id_created_at_0").val(start.format(format));
        $("#id_created_at_1").val(end.format(format));  
    }

    $('#filter-modal').on('shown.bs.modal', function () {
        console.log(moment($("#id_created_at_0").val()))
        var start_date = $("#id_created_at_0").val() ? moment($("#id_created_at_0").val()) : moment().subtract(29, 'days')
        var end_date = $("#id_created_at_1").val() ? moment($("#id_created_at_1").val()) : moment()
    
        $('#created_at').daterangepicker({
            startDate: start_date,
            endDate: end_date,
            showDropdowns: true,
            locale: {
                format: format,
            },
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start_date, end_date)

    })

});
</script>
{% endblock jsscript %}

expense/templates/expense/supplier_or_vendor.html
<!--Last Modified By:REMYA M S-->
{% extends "erp_admin/base.html" %}
{% load static %}
{% block content %}

<div class="banner">
    <h2>
        <a href="{% url 'expense:index' %}">Expense</a>
        <i class="fa fa-angle-right"></i>
        <span>Payee Type</span>
        <a href="{{ request.META.HTTP_REFERER }}"><i class="fa fa-times pull-right" aria-hidden="true"></i></a>

    </h2>
</div>

<div class="blank">
    <div class="grid-form1">
        <div class="tab-content">
            <div class="tab-pane active" id="horizontal-form">
                <form class="form-horizontal" action="{{ form_url }}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <div class="form-group">
                        <label for="subject" class="col-sm-2 control-label">{{ form.payee_type.label }}</label>
                        <div class="col-sm-4">{{ form.payee_type.errors }} {{ form.payee_type }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-4">
                            <button class="btn-primary btn pull-right">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>
{% endblock content %}
{% block jsscript %}
{% endblock jsscript %}