bill/urls.py
from django.conf.urls import url, include
# from expense.bill.urls import urlpatterns as bill_patterns
from . import views

app_name = 'bill'

urlpatterns = [
    # url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^list/$', views.list, name='list'),
    url(r'^add/$', views.add_bill, name='add_bill'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit_bill, name='edit_bill'),
    url(r'^(?P<pk>[^/]+)/details/$', views.detail, name='detail'),

]

calendarApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'calendarapp'

urlpatterns = [
    url(r'^send_whatsapp/(?P<invoice>[^/]+)/$', views.send_whatsapp, name="send_whatsapp"),
    url(r'^send_sms/(?P<invoice>[^/]+)/$', views.send_sms, name="send_sms"),
    url(r'^appointments/history/$', views.dateList, name='list'),
    url(r'^editstatus/(?P<pk>[^/]+)/$', views.editstatus, name='editstatus'),
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<pk>[^/]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<pk>[^/]+)/delete/$', views.delete, name='delete'),
    url(r'^dashboard/$', views.date, name='date'),
    url(r'^appointment/$', views.dashboard, name='dashboard'),
    url(r'^create/$', views.create, name="create"),
    url(r'^(?P<date>[-\w]+)/$', views.dateList, name='list'),
    url(r'^appointment/code/settings/$', views.code_settings, name='code_settings'),
]

invoice/urls.py
from django.conf.urls import url
from invoice import invoice_view


app_name = "invoice"



urlpatterns = [
    url(r'^invoice/create/$', invoice_view.createinvoice, name="createinvoice"),
    url(r'^invoice/(?P<pk>[^/]+)/createinvoice/$', invoice_view.createinvoice, name="createinvoice"),
    url(r'^invoice/createcustomer/$', invoice_view.createcustomer, name="createcustomer"),
    url(r'^invoice/(?P<pk>[^/]+)/edit/$', invoice_view.edit, name='edit'),
    url(r'^invoice/(?P<pk>[^/]+)/detail/$', invoice_view.detail, name='detail'),
    url(r'^invoice/(?P<pk>[^/]+)/delete/$', invoice_view.delete, name='delete'),
    url(r'^invoices/$', invoice_view.list_view, name='list'),
    url(r'^invoice/mail/settings/$', invoice_view.mail_settings, name='mail_settings'),
    url(r'^invoice/(?P<pk>[^/]+)/mail/$', invoice_view.invoice_mail, name='invoice_mail'),
    url(r'^invoice/code/settings/$', invoice_view.code_settings, name='code_settings'),
    url(r'^settings/$', invoice_view.settings_listing, name="settings"),
    url(r'^settings/locations/$', invoice_view.location_listing, name="location_listing"),
    url(r'^settings/locations/(?P<pk>[^/]+)/$', invoice_view.edit_location, name="edit_location"),
    url(r'^settings/add/$', invoice_view.create_location, name="create_location"),
    url(r'^sales/daily/report/(?P<from_date>[-\w]+)/(?P<to_date>[-\w]+)/$', invoice_view.daily_report, name="daily_report"),
    url(r'^sales/daily/report/$', invoice_view.daily_report, name="daily_report"),
    url(r'^invoice/(?P<pk>[^/]+)/detail.pdf/$', invoice_view.InvoicePDFView.as_view(), name="invoice_pdf"),
    url(r'^invoice/discount/(?P<pk>[^/]+)/(?P<customer_pk>[^/]+)/$', invoice_view.invoice_discount, name="invoice_discount"),
    url(r'^redeem/$', invoice_view.redeem, name='redeem'),
    url(r'^check_status/$', invoice_view.check_status),

]

papercraneerp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from sitetree.sitetreeapp import compose_dynamic_tree, register_dynamic_trees
from erp_admin import views as erpAdminViews
from rest_framework.authtoken import views

# from employee import views as employeeViews
from papercraneerp import allauth

urlpatterns = [
                  url(r'^$', erpAdminViews.dashboard),
                  url(r'^api-token-auth/', views.obtain_auth_token),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^accounts/password/change/$', allauth.login_after_password_change,
                      name='account_change_password'),  # Place before allauth urls to override
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^', include('employee.urls', namespace="employee")),
                  url(r'^', include('customer.urls', namespace="customer")),
                  url(r'^', include('product.urls', namespace="product")),
                  url(r'^chaining/', include('smart_selects.urls')),
                  url(r'^', include('service.urls', namespace="service")),
                  url(r'^', include('location.urls', namespace="location")),
                  url(r'^', include('invoice.urls', namespace="invoice")),
                  url(r'^', include('supplier.urls', namespace="supplier")),
                  url(r'^expense/', include('expense.urls', namespace="expense")),
                  url(r'^company/', include('company.urls', namespace="company")),
                  url(r'^vendor/', include('vendor.urls', namespace="vendor")),
                  url(r'^bill/', include('bill.urls', namespace="bill")),
                  url(r'^calendar/', include('calendarApp.urls', namespace="calendarApp")),
                  url(r'^discount/', include('discount.urls', namespace="discount")),
                  url(r'^package/', include('package.urls', namespace="package")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Saloon Administration'

register_dynamic_trees(
    compose_dynamic_tree('erp_admin'),
    compose_dynamic_tree('employee'),
    compose_dynamic_tree('service'),
    compose_dynamic_tree('product'),
    compose_dynamic_tree('package'),
    compose_dynamic_tree('discount'),
    compose_dynamic_tree('supplier'),
    compose_dynamic_tree('vendor'),
    compose_dynamic_tree('customer'),
    compose_dynamic_tree('calendarApp'),
    compose_dynamic_tree('invoice'),
    compose_dynamic_tree('expense'),

)

calendarApp/views.py
import datetime
import string
import random

import requests
from django.contrib import messages
from django.db import transaction
from django.forms import inlineformset_factory

from erp_core.pagination import paginate
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from datetime import datetime as dtime
from django.shortcuts import get_object_or_404, render

from invoice.models import Invoice
from .models import Appointment, AppointmentService, AppointmentCodeSetting
from .forms import DateForm, AppointmentServiceForm, AppointmentCodeSettingsForm
from .filters import DateFilter
from django.contrib.auth.decorators import login_required, permission_required
from django.core.mail import EmailMessage


@login_required
def date(request):
    dates = Appointment.objects.all()
    context = {
        'dates': dates,
    }
    return render(request, 'calapp/calapp.html', context)


@login_required
# @permission_required('calendarapp.view_appointment_list', raise_exception=True)
def detail(request, pk):
    dates = Appointment.objects.get(pk=pk)
    context = {
        'dates': dates,
        'statuses': Appointment.STATUS,
    }
    return render(request, 'calapp/detail.html', context)


@login_required
# @permission_required('calendarapp.view_appointment_list', raise_exception=True)
def dateList(request, date=None):
    reqDate = None
    if date:
        qs = Appointment.objects.filter(appointment_date_time__date=date)
        reqDate = '/calendar/' + date + '/'
    else:
        qs = Appointment.objects.all().order_by("-created_at")
        reqDate = ''
    f = DateFilter(request.GET, queryset=qs)
    dates, pagination = paginate(request, queryset=f.qs, per_page=10, default=True)
    context = {
        'dates': dates,
        'pagination': pagination,
        'filter': f,
        'reqDate': reqDate,
        'current_date': date
    }
    return render(request, "calapp/list.html", context)


@login_required
def dashboard(request):
    now = datetime.datetime.now()
    today = datetime.datetime.strptime(str(now.date()), "%Y-%m-%d")
    tomorrow = today + datetime.timedelta(days=1)
    # invoices = Invoice.objects.filter(paid_date__year=now.year)
    appointments = Appointment.objects.filter(office=request.user.employee.office, appointment_date_time__year=now.year)
    today_appointments = appointments.filter(appointment_date_time__date=today.date()).exclude(
        status=Appointment.CANCELLED)
    tomorrow_appointments = appointments.filter(appointment_date_time__date=tomorrow.date(), status=Appointment.NEW)[
                            :10]
    upcoming_appointments = today_appointments.filter(appointment_date_time__gte=now, status=Appointment.NEW)[:10]
    context = {
        'todays_appointments': today_appointments[:10],
        'tomorrow_appointments': tomorrow_appointments,
        'upcoming_appointments': upcoming_appointments,
        'todays_appointments_count': today_appointments.count(),
        'tomorrow_appointments_count': tomorrow_appointments.count(),
        'upcoming_appointments_count': upcoming_appointments.count(),
        'today': today.date(),
        'tomorrow': tomorrow.date(),

    }
    return render(request, 'calapp/dashboard.html', context)


@login_required
def send_payment_email(request, html_content, subject, email):
    try:
        msg = EmailMessage(subject, html_content, 'info@sinora.com',
                           [email])
        msg.content_subtype = "html"  # Main content is now text/html
        msg.send(fail_silently=False)
    except Exception as e:
        print(e)


@login_required
# @permission_required('calendarapp.change_appointment', raise_exception=True)
@transaction.atomic
def create(request):
    if request.GET.get('customer'):
        appointment_form = DateForm(request.POST or None, customer=request.GET.get('customer'))
    else:
        appointment_form = DateForm(request.POST or None, customer=None)

    ServiceInlineFormSet = inlineformset_factory(Appointment, AppointmentService, form=AppointmentServiceForm,
                                                 extra=0, can_delete=True, min_num=1, validate_min=True)

    service_formset = ServiceInlineFormSet(request.POST or None)
    if request.method == "POST":
        if appointment_form.is_valid() and service_formset.is_valid():
            appointment = appointment_form.save(commit=False)
            appointment.office = request.user.employee.office
            appointment.created_by = request.user
            appointment.save()
            services = service_formset.save(commit=False)

            for service in services:
                service.appointment = appointment
                service.save()

            html_content = "<p>Hi " + str(
                appointment.customer) + ",</p><p>Thank you! Your appointment on  " + str(
                appointment.appointment_date_time.date()) + "  at  " + str(
                appointment.appointment_date_time.time()) + " has been booked successfully.</p>"
            subject = "Appointment Booked"
            send_payment_email(request, html_content, subject, appointment.customer.email)
            message = "Hi " + str(
                appointment.customer) + ",Thank you! Your appointment with Sinora Beauty Salon  on  " + str(
                appointment.appointment_date_time.date()) + "  at  " + str(
                appointment.appointment_date_time.time()) + " has been booked successfully."

            send_sms(request, message, appointment.customer.phone)
            messages.add_message(request, messages.SUCCESS, 'Appointment added successfully!')

            return HttpResponseRedirect(reverse('calendarapp:list', args=(appointment.appointment_date_time.date(),)))

    context = {
        'appointment_form': appointment_form,
        'form_url': reverse_lazy('calendarapp:create'),
        'type': "Create",
        "service_formset": service_formset
    }
    return render(request, "calapp/edit.html", context)


@login_required
# @permission_required('calendarapp.change_appointment', raise_exception=True)
@transaction.atomic
def edit(request, pk):
    appointment = get_object_or_404(Appointment, id=pk)

    ServiceInlineFormSet = inlineformset_factory(Appointment, AppointmentService, form=AppointmentServiceForm,
                                                 extra=0, can_delete=True, min_num=1, validate_min=True)
    appointment_form = DateForm(request.POST or None, instance=appointment)
    service_formset = ServiceInlineFormSet(request.POST or None, instance=appointment)
    if request.method == "POST":
        if appointment_form.is_valid() and service_formset.is_valid():
            appointment = appointment_form.save(commit=False)
            appointment.office = request.user.employee.office
            appointment.save()

            services = service_formset.save(commit=False)
            for service in services:
                service.appointment = appointment
                service.save()
            messages.add_message(request, messages.SUCCESS, "Appointment edited successfully")
            return HttpResponseRedirect(reverse('calendarapp:list', args=(appointment.appointment_date_time.date(),)))

    context = {
        'appointment_form': appointment_form,
        'form_url': reverse_lazy('calendarapp:edit', args=[appointment.pk]),
        'service_formset': service_formset,
        'type': "Edit",
        'appointment': appointment,
    }
    return render(request, "calapp/edit.html", context)


@login_required
# @permission_required('calendarapp.change_appointment', raise_exception=True)
def editstatus(request, pk):
    if request.method == "POST":
        dateobj = Appointment.objects.get(pk=pk)
        status = request.POST.get('newstatus', None)
        dateobj.status = status
        dateobj.save()
        return HttpResponse(status)


@login_required
@permission_required('calendarapp.delete_appointment', raise_exception=True)
def delete(request, pk):
    dateobj = Appointment.objects.get(pk=pk)
    dateobj.delete()
    messages.add_message(request, messages.SUCCESS, "Appointment deleted successfully")
    return HttpResponseRedirect(reverse('calendarapp:date'))


@login_required
# @permission_required('calendarapp.view_appointment_list', raise_exception=True)
def upcoming_appointment(request):
    dateToday = datetime.date.today()
    date_1 = datetime.datetime.strptime(str(dateToday), "%Y-%m-%d")
    DateObject = Appointment.objects.all()
    upcoming_appointments = DateObject.filter(appointment_date_time__gte=dtime.now(),
                                              appointment_date_time__date=date_1.date(),
                                              office=request.user.employee.office)[:10]
    context = {
        'upcoming_appointments': upcoming_appointments,
    }
    return render(request, 'calapp/upcomingapp.html', context)


@login_required
# @permission_required('calendarapp.view_appointment_list', raise_exception=True)
def todays_appointment(request):
    dateToday = datetime.date.today()
    date_1 = datetime.datetime.strptime(str(dateToday), "%Y-%m-%d")
    DateObject = Appointment.objects.all()
    todays_appointments = DateObject.filter(appointment_date_time__date=date_1.date(),
                                            office=request.user.employee.office)[:10]
    context = {
        'todays_appointments': todays_appointments,
    }
    return render(request, 'calapp/todaysappointment.html', context)


@login_required
# @permission_required('calendarapp.view_appointment_list', raise_exception=True)
def tomorrows_appointment(request):
    dateToday = datetime.date.today()
    date_1 = datetime.datetime.strptime(str(dateToday), "%Y-%m-%d")
    next_day = date_1 + datetime.timedelta(days=1)
    DateObject = Appointment.objects.all()
    tomorrow_appointments = DateObject.filter(appointment_date_time__date=next_day.date(),

calendarApp/templates/calapp/calapp.html
{% extends "erp_admin/base.html" %}
{% load staticfiles %}
{% block head %}
<style type="text/css">
    .calendar-month-header{
        font-size:75px;
    }

@media screen and (max-width: 768px) {

  .calendar-month-header{
        font-size:45px;
    }

}
.dow-clickable:hover{
background-color:#d378f7!important;
}
</style>
<!-- include the calendar js and css files -->
<script src="{% static 'js/zabuto_calendar.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/zabuto_calendar.css' %}">

{% endblock head %}
{% block content %}
<div class="blank row" style="background-color: #fdf0ee;border-color:#fdf0ee;">
    <div class="blank-page col-xs-12" style="background-color: #fdf0ee;border-color:#fdf0ee;">


        <div id="my-calendar"></div>



    </div>
</div>
{% endblock content %}

{% block jsscript %}
<script type="text/javascript">

    window.onload = function() {
      $( ".badge-today" ).parent().parent().css( "background-color", "rgba(211, 120, 247, 0.33)" );
    };
    
    $(document).ready(function () {
        $('#my-calendar').zabuto_calendar({
        	cell_border: true,
			today: true,
			weekstartson: 0,
			nav_icon: {
			  prev: '<i class="fa fa-chevron-circle-left"></i>',
			  next: '<i class="fa fa-chevron-circle-right"></i>'
			},
            language: 'en',
            data : [
            	{% for dateobj in date_list %}		
				  {"date": '{{ dateobj }}' ,"badge":true,"title":"Example"},
				{% endfor %} 
				],
            action: function () {
            		{ myDateFunction(this.id); }
            }
        });
    });

    function myDateFunction(id) {
	    var date = $("#" + id).data("date");
	    var hasEvent = $("#" + id).data("hasEvent");
	    window.location = window.location.href.replace("/dashboard","")+date;
	}

</script>
{% endblock jsscript %}

calendarApp/templates/calapp/detail.html
{% extends "erp_admin/base.html" %}
{% load static tz %}
{% get_current_timezone as TIME_ZONE %}
{% block head %}
<style>
.btn{
text-align: left!important;
}
.cl{
padding:30px;
border: 1px solid rgb(234, 234, 234);
margin-left:3px;
}
.cl1{
padding:20px;
border: 1px solid rgb(234, 234, 234);
margin-left:20px;
margin-right:20px;
margin-top:0px!important;
}
.profile-bottom{
width:100%!important;
margin-bottom:0px!important;
}
.profile {
min-height: 294px!important;
}

.weather-bottom1{
width: 16% !important;
}

.badge-today{
color: #000 !important;
}

</style>
{% endblock head %}
{% block content %}

<div class="banner">
    <h2>
        <a href="{{ request.META.HTTP_REFERER }}">Appointments</a>
        <i class="fa fa-angle-right"></i>
        <span>{{ dates.customer }}</span>
        <a href="{{ request.META.HTTP_REFERER }}"><i class="fa fa-times pull-right" aria-hidden="true"></i></a>

    </h2>
</div>


<div class="content-bottom">
    <div class="col-md-12">
        <div class="weather">
            <div class="weather-top">
                <div class="weather-top-left">
                    <div class="degree">
                        <figure class="icons">
                            <i class="fa fa-user-circle-o fa-3x"></i>
                        </figure>
                        <span>{{ dates.customer }}</span>
                        <div class="clearfix"></div>
                    </div>

                    <p><i class="fa fa-calendar appointmentdate" data-id="{{ dates.appointment_date_time}}"></i>&nbsp; {{ dates.appointment_date_time}}
                    </p>
                </div>
                <div class="weather-top-right">
                    <p><i class="fa fa-phone"></i>{{ dates.customer.phone }}</p>

                </div>
                <div class="clearfix"></div>
            </div>
            <div class="weather-bottom">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th width="50%">Service</th>
                            <th width="50%">Employee</th>
                            <th width="50%">Price-AED</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for appointment in dates.services.all %}
                        <tr>
                            <td>{{ appointment.service }}</td>
                            <td><span class="badge">{{ appointment.employee }}</span></td>
                            <td>{{ appointment.service.price_hour }}</td>

                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            <div style="padding-left: 72px;padding-bottom:1%;">
                <br>
                {% if dates.status == 'cancelled' or dates.status == 'noshows' %}
                <a type="button" class="btn btn-primary" href="{% url 'calendarApp:edit' dates.pk %}">
                    <i class="fa fa-pencil-square" aria-hidden="true"></i> Rebook</a>
                {% else %}
                <a type="button" class="btn btn-primary" href="{% url 'calendarApp:edit' dates.pk %}">
                    <i class="fa fa-pencil-square" aria-hidden="true"></i> Edit</a>
                {% endif %}
                <a type="button" class="btn btn-danger" href="{% url 'calendarApp:delete' dates.pk %}"><i
                        class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                <div class="dropup">
                    <button class="btn btn-warning dropdown-toggle " type="button" data-toggle="dropdown">
                        <span class="statusdropdown">{{dates.status}}</span>
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        {% for status in statuses %}
                        {% if dates.status != status.0 %}
                        <li class='statuslist'><a href="#">{{status.0}}</a></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
{% endblock content %}

{% block jsscript %}
<script>
function remove(form, e){
    e.preventDefault()
    if(confirm('Confirm Delete')){
        form.submit()
    }
}

function getCookie(name) {
   var cookieValue = null;
   if (document.cookie && document.cookie != '') {
       var cookies = document.cookie.split(';');
       for (var i = 0; i < cookies.length; i++) {
           var cookie = jQuery.trim(cookies[i]);
           // Does this cookie string begin with the name we want?
           if (cookie.substring(0, name.length + 1) == (name + '=')) {
               cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
               break;
           }
       }
   }
   return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
   // these HTTP methods do not require CSRF protection
   return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
   beforeSend: function(xhr, settings) {
       if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
           xhr.setRequestHeader("X-CSRFToken", csrftoken);
       }
   }
});



$(document).ready(function() {
   $(".dropdown-menu li").click(function(event){
       var appoinment_date = Date.parse($('.appointmentdate').attr("data-id").slice(0,13).replace('.','').trim())
       if(appoinment_date > new Date() && $(this).text() == 'closed' ){
            alert('You cannot close an upcoming appointment')
       }
       else{
           $(".statusdropdown").text($(this).text())
           event.preventDefault();
           var elem = this;
           if (confirm("Are you sure?"))
           {
               $.ajax(
               {
                    url : '/calendar/editstatus/{{dates.pk}}/',
                   type: "POST",
                   data: {
                     'newstatus': ($(this).text())
                   },
                   success:function(data, textStatus)
                   {
                       accepted(elem);
                   },
                   error: function(jqXHR, textStatus, errorThrown)
                   {
                       $("#error_div").empty();
                       $("#error_div").html(jqXHR.responseText);
                   }
               });
           }else{
               return false;
           }
       }
       function accepted(elem) {
           elem = $(elem);
           if(elem.is(':checked'))
           {
               elem.prop('checked',false);
           }
           else
           {
               elem.prop('checked',true);
           }
       }
   });
   });



</script>

{% endblock jsscript %}

calendarApp/templates/calapp/list.html
{% extends "erp_admin/base.html" %}
{% load static tz %}
{% block head %}
<style type="text/css">
        
    .form-group{
            width:100%;
    }
    .tab-content {
    padding-left: 20px 
    }

</style>
{% endblock head %}

{% block content %}

<div class="banner">
    <h2>
        <a href="{% url 'calendarapp:date' %}">Appointments</a>
        <i class="fa fa-angle-right"></i>
        <span>{% if current_date %}{{current_date}} {% else %} All {% endif %}</span>
        <a href="{% url 'calendarApp:create' %}" class="btn btn-link"><i class="fa fa-plus-square-o fa-2x"></i></a>
        <a href="{{ request.META.HTTP_REFERER }}"><i class="fa fa-times pull-right" aria-hidden="true"></i></a>

    </h2>
</div>


<div class="blank">
    <div class="grid-form1">
        <div class="row">

        </div>

        <div class="row show-grid">
            <form id="search-form" method="get">
                <div class="col-sm-4">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-search"
                                                                             aria-hidden="true"></i></span>
                        <input  id="search" name="search" type="text" class="form-control" placeholder="Name,Phone,Email"
                               aria-describedby="basic-addon1" value="{{ request.GET.search }}">
                    </div>
                </div>
            </form>
            <a style="float:right;" href="{% url 'calendarapp:list' %}" class="btn btn-primary">
                    <i class="fa fa fa-refresh"></i>
                </a>
            <a style="float:right;" href="{% url 'calendarapp:code_settings' %}" class="btn btn-primary">
                    <i class="fa fa fa-cog"></i>
                </a>
        </div>

        <div class="row show-grid">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Date and time</th>
                            <th>Customer</th>
                            <th>Phone</th>
                            <th>Service</th>
                            <th>Status</th>
                            <th>Invoice</th>
                            <th>Edit</th>
                            {% if request.user.is_superuser %}
                            <th>Delete</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for dateobj in dates %}
                        {% if reqDate != 1 %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ dateobj.appointment_date_time|localtime }}</td>
                            <td><a href="{% url 'calendarApp:detail' dateobj.pk %}" class="btn btn-link">{{ dateobj.customer }}</a> </td>
                            <td>{{ dateobj.customer.phone }}</td>
                            <td>{% for appointment in dateobj.services.all %}
                                {{ appointment.service }}
                                {% if not forloop.last %},{% endif %}{% endfor %}</td>

                            <td>

                                <span class="{{dateobj.status|lower}}">{{dateobj.status}}</span>

                            </td>
                            <td>{% if dateobj.status != 'Closed' %}
                                    <a href="{% url 'invoice:createinvoice' %}?appointment_pk={{dateobj.pk}}" class="btn btn-pill btn-primary">Invoice <i class="fa fa-plus"></i></a>
                                {% else %}
                                    <a href="{% url 'customer:detail' dateobj.customer.pk %}" class="btn btn-link btn-secondary">View</a>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'calendarApp:edit' dateobj.pk %}" class="btn btn-link"><i
                                    class="fa fa-edit"></i></a></td>
                            {% if request.user.is_superuser %}
                            <td><a href="{% url 'calendarApp:delete' dateobj.pk %}" class="btn btn-link"><i
                                    class="fa fa-trash-o"></i></a></td>
                            {% endif %}
                        </tr>
                        {% endif %}
                        {% empty %}
                        <tr>
                            <td colspan="9">No Appointments</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block jsscript %}
<script src="{% static 'js/select2.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script src="/static/js/select2.js"></script>

<script>
$(document).ready(function(){

});

$('#search').on('input', function() {
  $('form#search-form').submit();
});

jQuery.fn.putCursorAtEnd = function() {

  return this.each(function() {

    // Cache references
    var $el = $(this),
        el = this;

    // Only focus if input isn't already
    if (!$el.is(":focus")) {
     $el.focus();
    }

    // If this function exists... (IE 9+)
    if (el.setSelectionRange) {

      // Double the length because Opera is inconsistent about whether a carriage return is one character or two.
      var len = $el.val().length * 2;

      // Timeout seems to be required for Blink
      setTimeout(function() {
        el.setSelectionRange(len, len);
      }, 1);

    } else {

      // As a fallback, replace the contents with itself
      // Doesn't work in Chrome, but Chrome supports setSelectionRange
      $el.val($el.val());

    }

    // Scroll to the bottom, in case we're in a tall textarea
    // (Necessary for Firefox and Chrome)
    this.scrollTop = 999999;

  });

};

(function() {

  var searchInput = $("#search");

  searchInput
    .putCursorAtEnd() // should be chainable
    .on("focus", function() { // could be on any event
      searchInput.putCursorAtEnd()
    });

})();


</script>
{% endblock jsscript %}